name: Build MacOS

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: brew
      run: brew install --cask macfuse

    - name: compile fuse
      run: clang++ -std=c++14 -Wall main.cpp `pkg-config fuse --cflags --libs` -o ii-part-fuse

