name: Build Ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: apt-get
      run: sudo apt-get install libfuse-dev

    - name: compile fuse 2
      run: g++ -std=c++14 -Wall -Wno-sign-compare main.cpp `pkg-config fuse --cflags --libs` -o ii-part-fuse
